qa: deepsea: fix rpmspec call for SES6
The "-v" option causes rpmspec to emit the following error on a Python 3-only system:

error: incorrect format: array iterator used with different sized arrays

References: https://bugzilla.suse.com/show_bug.cgi?id=1083861
Signed-off-by: Nathan Cutler <ncutler@suse.com>